project:
  type: website
  preview:
    port: 4200
  output-dir: _site

website:
  title: "Programación II"
  description: "Página del curso Programación II - FCEyE (UNR)."
  site-url: "https://ee-unr.github.io/programacion-2/"
  favicon: imgs/terminal-64.png
  page-navigation: true
  navbar:
    pinned: true
    right:
      - text: Información
        file: informacion/programa.qmd
      - text: Teoría
        file: teoria/01_introduccion_a_python/clase_1.ipynb
      - text: Práctica
        file: practica/01_introduccion_a_python.qmd
      - text: Trabajos Prácticos
        file: trabajos_practicos/descripcion.qmd
      - text: Recursos
        file: recursos/ejercicios/ejercicio_01.qmd
      - icon: github
        href: "https://github.com/ee-unr/programacion-2"

  sidebar:
    - title: Información
      contents:
        - informacion/programa.qmd
        - informacion/aprobacion.qmd
        - informacion/calendario.qmd
        - informacion/bibliografia.qmd
        # - informacion/faq.qmd
    - title: Teoría
      contents:
        - text: U1 - Introducción a Python
          contents:
            - auto: teoria/01_introduccion_a_python/*.ipynb
            - sort-ui: false
        - teoria/02_programacion_funcional.qmd
        - teoria/03_oop.qmd
        - teoria/04_estructuras.qmd
        - teoria/05_algoritmos.qmd
    - title: Práctica
      contents:
        - practica/01_introduccion_a_python.qmd
        - practica/02_programacion_funcional.qmd
        - practica/03_oop.qmd
        - practica/04_estructuras.qmd
        - practica/05_algoritmos.qmd
    - title: Trabajos Prácticos
      contents:
        - trabajos_practicos/descripcion.qmd
        - trabajos_practicos/trabajo_grupal.qmd
        - trabajos_practicos/trabajo_individual.qmd
    - title: Recursos
      contents:
        - text: Ejercicios
          file: recursos/ejercicios/ejercicio_01.qmd
          contents:
            - auto: recursos/ejercicios/*.qmd
            - sort-ui: false
        - text: Tutoriales
          file: recursos/tutoriales/tutorial_01.qmd
          contents:
            - auto: recursos/tutoriales/*.qmd
            - sort-ui: false

  page-footer:
    right: "Esta página es hecha con ❤️ y [Quarto](https://quarto.org/)."

format:
  html:
    theme: styles.scss
    toc: false
    lang: es

bibliography: citas/references.bib
csl: citas/chicago-author-date.csl