project:
  type: website
  preview:
    port: 4200
  output-dir: _site


website:
  title: "Programación II"
  description: "Página del curso Programación II - FCEyE (UNR)."
  site-url: "https://ee-unr.github.io/programacion-2/"
  favicon: imgs/terminal-64.png
  page-navigation: true
  navbar:
    pinned: true
    right:
      - text: Información
        file: informacion/programa.qmd
      - text: Teoría
        file: teoria/01_programacion_en_python/01_introduccion.ipynb
      - text: Práctica
        file: practica/01_programacion_en_python/ejercicios.qmd
      - text: Trabajos Prácticos
        file: trabajos_practicos/trabajo_grupal.qmd
      - text: Recursos
        file: recursos/tutoriales/tutorial_01.qmd
      - icon: github
        href: "https://github.com/ee-unr/programacion-2"

  sidebar:
    - title: Información
      contents:
        - informacion/programa.qmd
        - informacion/aprobacion.qmd
        - informacion/calendario.qmd
        - informacion/bibliografia.qmd
        # - informacion/faq.qmd
    - title: Teoría
      contents:
        - text: U1 - Programación en Python
          contents:
            - auto: teoria/01_programacion_en_python/*.ipynb
            - sort-ui: false
        - text: U2 - Programación Funcional
          contents:
            - auto: teoria/02_programacion_funcional/*.ipynb
            - sort-ui: false
        - text: U3 - Programación Orientada a Objetos
          contents:
            - auto: teoria/03_oop/*.ipynb
            - sort-ui: false
        - text: U4 - Estructuras de Datos y Algoritmos
          contents:
            - auto: teoria/04_estructuras_y_algoritmos/*.ipynb
            - sort-ui: false
    - title: Práctica
      collapse-level: 2
      collapse: true
      contents:
        - text: U1 - Programación en Python
          contents:
            - practica/01_programacion_en_python/autoevaluacion.qmd
            - practica/01_programacion_en_python/ejercicios.qmd
            - practica/01_programacion_en_python/problemas.qmd
        - text: U2 - Programación funcional
          contents:
            - practica/02_programacion_funcional/autoevaluacion.qmd
            - practica/02_programacion_funcional/ejercicios.qmd
            - practica/02_programacion_funcional/problemas.qmd
        - text: U3 - Programación Orientada a Objetos
          contents:
            - practica/03_oop/autoevaluacion.qmd
            - practica/03_oop/ejercicios.qmd
            - practica/03_oop/problemas.qmd
        - text: U4 - Estructuras de Datos y Algoritmos
          contents:
            - practica/04_estructuras_y_algoritmos/autoevaluacion.qmd
            - practica/04_estructuras_y_algoritmos/ejercicios.qmd
            - practica/04_estructuras_y_algoritmos/problemas.qmd
    - title: Trabajos Prácticos
      contents:
        - trabajos_practicos/trabajo_grupal.qmd
        - trabajos_practicos/trabajo_individual.qmd
    - title: Recursos
      contents:
        - text: Ejemplos
          file: recursos/ejemplos/01_funciones_y_bucles.qmd
          contents:
            - auto: recursos/ejemplos/*.qmd
            - sort-ui: false
        - text: Ejercicios
          contents:
          - text: U1 - Programación en Python
            file: recursos/ejercicios/01_programacion_en_python/index.qmd
          - text: U2 - Programación funcional
            file: recursos/ejercicios/02_programacion_funcional/index.qmd
        - text: Tutoriales
          file: recursos/tutoriales/tutorial_01.qmd
          contents:
            - auto: recursos/tutoriales/*.qmd
            - sort-ui: false

  page-footer:
    right: "Esta página es hecha con ❤️ y [Quarto](https://quarto.org/)."

format:
  html:
    theme: styles.scss
    toc: false
    lang: es

bibliography: citas/references.bib
csl: citas/chicago-author-date.csl
