---
title: "🛠️ Ejercicios"
---

## Área y perímetro de un círculo

Escriba una función en Python que reciba el radio de un círculo y devuelva su área.
Luego, escriba otra función que también reciba el radio de un círculo, pero devuelva su perímetro.
Finalmente, escriba una tercera función que reciba el radio de un círculo y devuelva tanto el área 
como el perímetro.

<!-- Para este último caso, implemente dos versiones:

1. La función devuelve una lista o tupla.
2. La función devuelve un diccionario.

¿Cuáles son las ventajas y desventajas de cada alternativa?

 -->

::: {.callout-tip collapse="true"}

### Ayuda

$$
\begin{aligned}
A &= \pi \cdot r^2 \\
P &= 2 \cdot \pi \cdot r
\end{aligned}
$$

:::

## Promociones

Escriba una función llamada `calcular_precio_final` que reciba dos argumentos:
el monto total de una compra y el medio de pago utilizado.

El medio de pago puede ser `'efectivo'`, `'débito'` o `'crédito'`, y según el caso se aplicará una
modificación sobre el monto:

- Si el medio de pago es `'efectivo'`, el monto no se modifica.
- Si es `'débito'`, se aplica un descuento del 10% sobre el monto.
- Si es `'crédito'`, se aplica un recargo del 5% sobre el monto.

La función debe retornar el monto final a pagar, con el descuento o recargo aplicado según
corresponda.

## Etapas de la vida

Implemente una función que reciba una edad y devuelva un mensaje que indique la etapa de la vida
correspondiente.

Utilice una cadena de condicionales `if-elif-else` para clasificar la edad en alguno de los
siguientes grupos:

- Menor a 2 años: bebé.
- Entre 2 (inclusive) y 4 años: infante.
- Entre 4 (inclusive) y 13 años: niño/a.
- Entre 13 (inclusive) y 20 años: adolescente.
- Entre 20 (inclusive) y 65 años: adulto/a.
- 65 años o más: persona mayor.

La función debe imprimir un mensaje del tipo: `"La persona es un/a <etapa>"`.

## Conteo de frecuencias

Implemente una función que reciba una lista de palabras y devuelva un diccionario donde las claves
sean las palabras y los valores la cantidad de veces que aparece cada una.
Utilice el siguiente ejemplo como validación:

```python
contar_frecuencias(["manzana", "naranja", "manzana", "pera", "pera", "manzana"])
# {"manzana": 3, "naranja": 1, "pera": 2}
```

## Rendimento académico

Se cuenta con el siguiente diccionario que asocia nombres de estudiantes con una lista de sus
calificaciones:

```python
notas = {
    "Ana": [8, 9, 10],
    "Luis": [6, 7, 8, 3, 9],
    "Carla": [10, 9, 10],
    "Marcos": [5, 6],
    "Sofía": [7, 7, 8],
    "Pedro": [6, 4, 5, 6, 3, 8],
    "Lucía": [9, 8, 10, 9]
}
```

Implemente una función que resuma el rendimiento académico de los estudiantes.
La función debe recibir el diccionario de notas y un argumento adicional llamado `modo`.
Según el valor de `modo`, se debe devolver un nuevo diccionario con la siguiente información:

* Si modo es `"promedio"`, se debe devolver el promedio de notas por estudiante.
* Si modo es `"proporcion"|, se debe devolver la proporción de exámenes aprobados por estudiante
(se considera aprobado todo valor mayor o igual a 6).

## Índice de precios

Se cuenta con la serie mensual del Índice de Precios al Consumidor (IPC) del año 2024:

```python
ipc_2024 = [20.6, 13.2, 11.0, 8.8, 4.2, 4.6, 4.0, 4.2, 3.5, 2.7, 2.4, 2.7]
```

Realice los siguientes cálculos y análisis:

* Determine el menor y el mayor índice reportado durante el año.
* Calcule el IPC promedio mensual del 2024.
* Encuentre la diferencia entre el IPC mínimo y máximo del año.
    - ¿En qué mes se registró la inflación más alta?
* Calcule la inflación mediana del 2024.
* ¿Cómo podría calcular el rango del IPC (diferencia entre el valor máximo y mínimo) sin usar
las funciones `min()` ni `max()`?

## Resúmenes estadísticos

Cree funciones que, dada una lista de números, calculen los siguientes resúmenes estadísticos:

i. La media
    $$
    \text{media}(X) = \frac{1}{n}\sum_{i=1}^n{x_i}
    $$
i. El rango
    $$
    \text{rango}(X) = \text{max}(X) - \text{min}(X)
    $$
i. La varianza
    $$
    \text{var}(X) = \frac{1}{n}\sum_{i=1}^n{(x_i - \bar{x})^2}
    $$
i. El desvío estándar
    $$
    \text{sd}(X) = \sqrt{\text{var}(X)}
    $$
i. La mediana
    $$
    \begin{array}{lr}
    \text{mediana}(X) = x_{(\frac{n + 1}{2})} & \text{Si } n \text{ es impar} \\
    \text{mediana}(X) = \frac{x_{(\frac{n}{2})} + x_{(\frac{n}{2}+1)}}{2} & \text{Si } n \text{ es par}
    \end{array}
    $$

    donde los $x_{(i)}$ están ordenados de manera ascendente.

## Potencias

Escriba una función que reciba un número entero `n` y una potencia máxima `b`.
La función debe calcular las potencias de `n` desde $n^1$ hasta $n^b$.
Primero, implemente la función para que devuelva todas las potencias en una lista.
Luego, modifique la función para que devuelva cada potencia como un valor separado.
Reflexione sobre las diferencias entre devolver una lista
(un único objeto que contiene todos los resultados) y devolver múltiples valores separados.

## La física del rebote

Una pelota de goma es lanzada desde una altura inicial de 100 metros.
Cada vez que toca el suelo, rebota alcanzando una altura equivalente a 3/5 de la altura desde
la que cayó.

Escriba un programa que imprima una tabla mostrando las alturas alcanzadas por la pelota en
cada uno de sus primeros 10 rebotes.

Luego, implemente este programa como una función que reciba dos parámetros:

* Altura inicial desde la que se lanza la pelota.
* Cantidad de rebotes que se desea calcular.

La función debe devolver una lista con las alturas alcanzadas en cada rebote.

### Punto extra

Modifique la función para que considere un rebote como "significativo" solo si la altura
alcanzada es mayor o igual a un valor mínimo especificado (por ejemplo, 1 centímetro).

Si la pelota no alcanza esta altura mínima en algún rebote, se considera que ha completado su
aterrizaje y queda quieta. En este caso, la función debe devolver únicamente los valores
correspondientes a los "rebotes significativos"

## Validación de DNI

Crear una función que dada una cadena de caracteres verifique si se corresponde con un DNI.

Si es un DNI, devolver `True`. Caso contrario, devolver `Falso`.

A tener en cuenta:

* Algunos ejemplos de DNI válidos
    * 39.979.127
    * 39979127
    * 4.497.785
* DNI no válidos
    * 39,979,127
    * 39-979-127
    * 123456
    * ...

## Un montón de plata

Una mañana ponés un billete en la vereda al lado del Monumento a la Bandera.
A partir de ahí, cada día vas y duplicás la cantidad de billetes, apilándolos prolijamente.
¿Cuánto tiempo pasa antes de que la pila de billetes sea más alta que la del Monumento?

::: {.callout-tip collapse="true"}

### Ayuda

Algunas constantes útiles para resolver el problema:

```python
billete_grosor = 0.11 * 0.001  # grosor de un billete en metros
altura_monumento = 70          # altura en metros
```

**Sugerencia**: Usar un bucle `while` para realizar el cálculo.
:::

### Punto extra

Escribe una función que permita determinar la cantidad de días necesarios para superar
cualquier altura arbitraria.

## La conjetura de Collatz

La [conjetura de Collatz](https://es.wikipedia.org/wiki/Conjetura_de_Collatz) dice:

> Si tomamos un número natural cualquiera, su secuencia de Collatz termina llegando siempre al
número 1.

Secuencia de Collatz:

* Si el número es par, se divide entre 2.
* Si el número es impar, se multiplica por 3 y se le suma 1.

$$
f(n) =
\begin{cases}
    \displaystyle \frac{n}{2} & \text{si } n \text{ es par,} \\ \\
    3n + 1 & \text{si } n \text{ es impar.}
\end{cases}
$$

Escribir una función que calcule la secuencia de Collatz para un número natural cualquiera.

::: {.callout-tip collapse="true"}

### Ayuda

* Utilizar bucle `while`.
* El bucle debe correr solo cuando el valor de la secuencia sigue siendo mayor a 1.
Si es 1, hay que frenar.
* Insertar los elementos de la secuencia en una lista.

:::

## Adivina el número

Escriba un programa que implemente el clásico juego "Adivina el número".

El programa debe:

1. Tener un número secreto (entero) que el usuario debe adivinar.
2. Solicitar al usuario que ingrese un número.
3. Si el número ingresado no coincide con el número secreto:
    * Informar si el número ingresado es mayor o menor que el número secreto.
    * Pedir al usuario que intente nuevamente.
4. Si el usuario adivina el número, el programa debe terminar mostrando un mensaje de felicitaciones.

::: {.callout-tip collapse="true"}

### Ayuda

Para generar números aleatorios enteros en un rango dado puede utilizar `randint()` del módulo
`random`:

```python
import random
random.randint(-100, 100)     # Genera un número aleatorio entre -100 y 100
```

:::

## Validador de contraseñas

Escriba un programa que solicite al usuario una contraseña y verifique que cumpla con las
siguientes condiciones:

* Debe tener entre de 8 y 24 caracteres.
* Debe incluir letras, números y caracteres especiales (`@#$%^&*()`).

Si la contraseña no es válida, el programa debe informar al usuario qué condición no se cumple
y permitirle ingresar una nueva contraseña.
El proceso se repite hasta que el usuario ingrese una contraseña válida o decida no continuar.

## Conteo de frecuencias a medida

Agregue a la función `contar_frecuencias` del ejercicio **Conteo de frecuencias** un argumento
llamado `orden` que admita los valores `"aparicion"`, `"alfabetico"` y `"frecuencia"`.

Este argumento debe permitir ordenar las claves del diccionario resultante según el siguiente
criterio:

* `"aparicion"`: mantiene el orden en que las palabras aparecen por primera vez en la lista original.
* `"alfabetico"`: ordena las palabras alfabéticamente.
* `"frecuencia"`: ordena las palabras por su frecuencia, de mayor a menor.


## Control interno (ELIMINAR)

* [ ] Tipo de datos elementales (agregar en **Preguntas**)
* [ ] Asignación múltiple
* [x] Desestructuración (se podría profundizar más)
* [x] Operadores numéricos
* [x] Operadores lógicos
* [x] Definición de funciones.
* [x] Ejecución condicional de código.
* Bucles definidos y no definidos
    * [x] `for`
    * [x] `while`
    * [ ] `break` (no estoy seguro de haberlo incluido)
    * [ ] `continue` (no estoy seguro de haberlo incluido)
* Estructuras de datos nativas de Python
    * [x] listas
    * [ ] tuplas (puede que haya, pero agregar más)
    * [ ] conjuntos (no es tan necesario, aparece más adelante)
    * [ ] diccionarios
    * [x] `range`
* Uso de código externo (propio y de terceros).
    * [x] Librería estándar de Python.
    * [x] Scripting.
    * [x] Modularización de programas.

### Comentarios

Temas que no son necesarios de cubrir _per se_ en la práctica:

* Expresiones
* Variables y asignación
* Módulos y librerías (cubierto en clases de teoría y de manera implícita en otros temas)
* Instalación y gestión de librerías (va a aparecer mucho más adelante).



<!-- ## Conteo de palabras

Construya una función que reciba una cadena de texto y devuelva un diccionario donde las claves
sean las palabras y los valores la cantidad de veces que aparece cada una. Para ello, realice
dos implementaciones

### Implementación 1

Utilice el método `.split()` para 


Además, incorpore un
argumemento booleano llamado `ordenado` que permita determinar si las palabras se ordenan
según orden de aparición o s


 lista de palabras y devuelva un diccionario donde las claves sean las palabras y los valores la cantidad de veces que aparece cada una. 
 
 

## Calculadora de variación porcentual

Construya un programa que calcule cómo ha variado un precio de un producto o servicio a lo
largo de una o varias semanas.

El programa debe pedir al usuario:

* Precio inicial
* Precio final
* Cantidad de semanas entre precios.

E imprimir un mensaje que incluya la variación porcentual entre periodos y una variación
porcentual anualizada.


## Persiguiendo la meta

En el Parque Independencia, la pista de atletismo del Estadio Municipal tiene una longitud de
400 metros. Lucio, un atleta rosarino, se estuvo preparando intensamente para una competencia de
400 los metros llanos.

En su cuenta de Instagram, Lucio publicó una historia que decía:

> "20 días, 100 kilómetros, 1 objetivo."

### Parte 1: Análisis inicial

Con base en esta información, responde las siguientes preguntas:

i. ¿Cuántos metros corrió Lucio por día en promedio?
i. ¿Cuántas vueltas completas dio por día en promedio? ¿Le sobró algún metro? ¿Cuántos?
i. ¿Cuántas vueltas completas dio en total durante los 20 días?

### Parte 2: Planificando el entrenamiento

Lucio está diseñando un plan de entrenamiento para su próxima competencia.
Quiere saber cuántas vueltas dará en promedio por día y cuántas vueltas completará en total al
final de su entrenamiento.

Escribe un programa que reciba:

* Días de entrenamiento (un número entero).
* Cantidad de metros a correr por día (un número entero).

Y que devuelva:

* Vueltas completas promedio por día (en una pista de 400 metros).
* Vueltas completas totales al final del entrenamiento.
* Metros sobrantes por día, si los hay.

### Parte 3: Plan de entrenamiento avanzado

Lucio quiere un programa más flexible para planificar su entrenamiento.
Ahora, además de los días de entrenamiento, quiere poder ingresar la cantidad total de vueltas
**o** la cantidad total de kilómetros que planea correr.

Escribe un programa que reciba:

* Días de entrenamiento (un número entero).
* Cantidad total de vueltas o cantidad total de kilómetros
(el usuario debe elegir una de las dos opciones).

Y que devuelva:

* Cantidad de metros y vueltas promedio por día.
* Cantidad total de metros y vueltas.


## Números impares

Utilice el tercer argumento de la función `range()` para construir una lista con los números impares
del 1 al 20. Luego, utilice un ciclo `for` para imprimir cada uno de ellos.

## Cubos

Un número elevado a la tercera potencia se llama **cubo**. Por ejemplo, el cubo de 2 se escribe como
`2**3` en Python.

Cree una lista con los primeros 10 cubos (es decir, el cubo de los números del 1 al 10).
Luego, utilice un ciclo `for` para imprimir el valor de cada cubo.

 -->