---
title: Condiciones de aprobación
---

## Instancias de evaluación

📝 **Examen parcial**: individual y escrito. Hay un recuperatorio, de similares características,
que reemplaza la nota del parcial.

🤝 **Trabajo práctico grupal**: se hace fuera de clase, en grupos de entre dos y tres integrantes.

🧑‍💻 **Trabajo práctico individual**: opcional para promoción, con presentación y defensa oral.

Todas las instancias se califican en una escala de 0 a 10 y se aprueban con 6.

## Condiciones de aprobación

**Promoción**
: Quienes aprueben el parcial individual (con nota $\text{P}$), el trabajo práctico grupal
(con nota $\text{T}$) y el trabajo práctico individual con defensa oral (con nota $\text{O}$),
adquieren la condición de estudiante promovido y su nota final se calcula como
$0.5 \times \text{P} + 0.2 \times \text{T} + 0.3 \times \text{O}$.

**Regularidad**
: Quienes aprueben el parcial individual (o su recuperatorio) y el trabajo práctico grupal,
pero no accedan o no aprueben el trabajo práctico individual, adquieren la condición de
estudiante regular.

**Libres**
: Quienes no aprueben el parcial individual (ni su recuperatorio) o el trabajo práctico grupal,
adquieren la condición de estudiante libre.
